/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2024-10-17 08:46:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1729040514560L));
    _jspx_dependants.put("/common/main_header.jsp", Long.valueOf(1729150391494L));
    _jspx_dependants.put("/common/right_menu.jsp", Long.valueOf(1729057850345L));
    _jspx_dependants.put("/common/footer.jsp", Long.valueOf(1729057892408L));
    _jspx_dependants.put("jar:file:/C:/back/jsp/jsp_1016/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Web_01/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/productUpdate.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"script/product.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <!-- 헤더 시작 -->\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <!-- 헤더 상단 -->\r\n");
      out.write("        <div class=\"header_top\">\r\n");
      out.write("            <h1 class=\"logo\">\r\n");
      out.write("                <a href=\"ModernServlet?command=mdh_main&userid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    <img src=\"./img/tlogo.png\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </h1>\r\n");
      out.write("            <div class=\"mall_switch\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"ModernServlet?command=mdh_main&userid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"link_modern on\">모던몰</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"ModernServlet?command=mdh_sub\" class=\"link_butter\">버터샵</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"search_area\">\r\n");
      out.write("                <input type=\"text\">\r\n");
      out.write("                <a href=\"#\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"top_right\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"ModernServlet?command=mdh_logout\">\r\n");
      out.write("                            <img src=\"./img/icon_logout.png\" alt=\"\">\r\n");
      out.write("                            <span >로그아웃</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"ModernServlet?command=mdh_update_form&userid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                            <img src=\"./img/icon_mypage.png\" alt=\"\">\r\n");
      out.write("                            <span class=\"join_span\">마이페이지</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./img/icon_cart.png\" alt=\"\">\r\n");
      out.write("                            <span>장바구니</span>\r\n");
      out.write("                            <span class=\"cart_num\">0</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./img/icon_call.png\" alt=\"\">\r\n");
      out.write("                            <span>고객센터</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 헤더 하단 메뉴 부분 -->\r\n");
      out.write("        <div class=\"header_menu\">\r\n");
      out.write("            <div class=\"menu_left\">\r\n");
      out.write("                <div class=\"menu_icon\"></div>\r\n");
      out.write("                <div class=\"cate\">카테고리</div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 마우스 오버 메뉴 -->\r\n");
      out.write("                <div class=\"mainmenu\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">주방</a>\r\n");
      out.write("                            <ul class=\"submenu sub0\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">NEW</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">식기류</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">수저/커트러리</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">컵/잔</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">보틀/텀블러</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">테이블소품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">팬/냄비</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">커피/티 용품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">조리도구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">보관용기</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">주방수납/정리</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">주방잡화</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">패브릭</a>\r\n");
      out.write("                            <ul class=\"submenu sub1\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">NEW</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">침구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">알러지케어</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">담요/블랭킷</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">충전재</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">커튼/블라인드</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">쿠션/방석/패드</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">러그/매트</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">패브릭소품</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">가구</a>\r\n");
      out.write("                            <ul class=\"submenu sub2\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">침실가구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">주방가구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">거실가구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">책상/책장/의자</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">서랍/수납/선반장</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">옷장/행거</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">키즈가구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">택배가구</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">키즈</a>\r\n");
      out.write("                            <ul class=\"submenu sub3\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">키즈플레이</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">키즈침구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">키즈식기/주방</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">키즈욕실</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">키즈가구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">키즈잡화</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">린넨앤키친</a>\r\n");
      out.write("                            <ul class=\"submenu sub4\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">패브릭</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">주방</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">리빙데코</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">욕실/생활</a>\r\n");
      out.write("                            <ul class=\"submenu sub5\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">청소용품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">휴지통/재활용</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">세탁/건조용품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">바디/위생용품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">욕실/생활잡화</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">타올/가운</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">욕실화</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">우산/우의</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">일회용품</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">홈데코</a>\r\n");
      out.write("                            <ul class=\"submenu sub6\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">인테리어 소품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">캔들/디퓨저</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">홈앤가든</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">수납/정리</a>\r\n");
      out.write("                            <ul class=\"submenu sub7\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">의류수납</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">바구니/박스</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">아이템정리</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">선반/트롤리/카트</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">가전/라이프</a>\r\n");
      out.write("                            <ul class=\"submenu sub8\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">가전/디지털</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">여행</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">플레이</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">펫본</a>\r\n");
      out.write("                            <ul class=\"submenu sub9\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">하우스</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">방석/매트/계단</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">장난감</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">식기</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">간식</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">의류</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">액세서리</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">위생용품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">가방</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">뷰티용품</a>\r\n");
      out.write("                            <ul class=\"submenu sub10\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">개인위생용품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">리필용기</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">미용소도구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">헤어소품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">시즌잡화</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">주전부리</a>\r\n");
      out.write("                            <ul class=\"submenu sub11\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">건강간식</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">달콤간식</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">건강티백</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"menu_right\">\r\n");
      out.write("                <li><a href=\"ModernServlet?command=mdh_sub\">#썸머 핫딜</a></li>\r\n");
      out.write("                <li><a href=\"ModernServlet?command=mdh_sub\">베스트</a></li>\r\n");
      out.write("                <li><a href=\"ModernServlet?command=mdh_sub\">신상품</a></li>\r\n");
      out.write("                <li><a href=\"ModernServlet?command=mdh_sub\">SALE</a></li>\r\n");
      out.write("                <li><a href=\"ModernServlet?command=mdh_sub\">쿠폰/혜택</a></li>\r\n");
      out.write("                <li><a href=\"ModernServlet?command=admin_check\">상품관리</a></li>\r\n");
      out.write("                <li><a href=\"ModernServlet?command=review_list\">REVIEW</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- 우측 하단 고정메뉴 -->\r\n");
      out.write("    <div class=\"right_menu\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img src=\"./img/quick_icon01.png\" alt=\"\">\r\n");
      out.write("                    <span>0</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img src=\"./img/quick_icon02.png\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img src=\"./img/quick_icon03.png\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("		</ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrap\" align=\"center\">\r\n");
      out.write("          <h1 class=\"title\">상품 수정</h1>\r\n");
      out.write("          <form method=\"post\" enctype=\"multipart/form-data\" name=\"frm\" action=\"ModernServlet?command=product_update\">\r\n");
      out.write("            <input type=\"hidden\" name=\"code\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"nonmakeImg\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pictureUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            <table class=\"cover\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td class=\"img_box\">\r\n");
      out.write("                  ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("                <td class=\"info\">\r\n");
      out.write("                  <table>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th style=\"width:80px\"> 상품명</th>\r\n");
      out.write("                      <td>\r\n");
      out.write("                        <input type=\"text\" name=\"productname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.productName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" size=\"80\">\r\n");
      out.write("                      </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th>가격</th>\r\n");
      out.write("                      <td><input style=\"width:10%\" type=\"text\" name=\"price\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> 원</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th>사진</th>\r\n");
      out.write("                      <td>\r\n");
      out.write("                        <input type=\"file\" name=\"pictureUrl\"><br>\r\n");
      out.write("                      </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <th>설명</th>\r\n");
      out.write("                      <td><textarea cols=\"90\" rows=\"10\" name=\"description\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("                </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <input class=\"sub_btn\" type=\"submit\" value=\"수정\" onclick=\"return productCheck()\">\r\n");
      out.write("            <input class=\"other_btn\" type=\"reset\" value=\"다시 작성\">\r\n");
      out.write("            <input class=\"other_btn\" type=\"button\" value=\"목록\" onclick=\"location.href='ModernServlet?command=product_list'\">\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- 푸터 시작 -->\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        <div class=\"footer_box\"> \r\n");
      out.write("            <div class=\"logobox\">\r\n");
      out.write("                <div class=\"ftlogo\">\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <img src=\"./img/flogonew.png\" alt=\"\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"snslogo\">\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"./img/footer_sns01.png\" alt=\"\"></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"./img/footer_sns03.png\" alt=\"\"></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"./img/footer_sns04.png\" alt=\"\"></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"./img/footer_sns05.png\" alt=\"\"></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"infobox\">\r\n");
      out.write("                <div class=\"linklist\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">회사소개</a></li>\r\n");
      out.write("                        <li><a href=\"#\">IR</a></li>\r\n");
      out.write("                        <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                        <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("                        <li><a href=\"#\">1:1문의</a></li>\r\n");
      out.write("                        <li><a href=\"#\">대량/제휴문의</a></li>\r\n");
      out.write("                        <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("                        <li><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"companyinfo\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>주소 : 서울특별시 구로구 경인로 662 (디큐브시티) 14층</li>\r\n");
      out.write("                        <li>회사명 : MH&CO.</li>\r\n");
      out.write("                        <li>대표이사 : 오상흔</li>\r\n");
      out.write("                        <li>사업자등록번호 : 821-87-00617</li>\r\n");
      out.write("                        <li>통신판매업번호 : 2017-서울구로-1368</li>\r\n");
      out.write("                        <li>개인정보책임자 : 이효영</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"certifyinfo\">\r\n");
      out.write("                    <span>고객님은 안전거래를 위해 결제 시 저희 사이트에서 가입한 구매안전 서비스를 이용하실 수 있습니다.</span>\r\n");
      out.write("                    <a href=\"#\">KCP 가입 확인</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p>copyright. 2020. modernhousemall.com. All rights reserved.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"csbox\">\r\n");
      out.write("                <h3>고객문의 대표전화</h3>\r\n");
      out.write("                <h2>1899-0811</h2>\r\n");
      out.write("                <p>AM 09:00 ~ PM 06:00 <br>(주말 · 공휴일 휴무)</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>  \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /product/productUpdate.jsp(30,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty product.pictureUrl}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                      <img style=\"width:80%\" src=\"img/noimage.gif\">\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                      <img style=\"width:80%\" src=\"upload/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pictureUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
