/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2024-10-17 07:34:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/common/main_header.jsp", Long.valueOf(1729150391494L));
    _jspx_dependants.put("/common/right_menu.jsp", Long.valueOf(1729057850345L));
    _jspx_dependants.put("/common/footer.jsp", Long.valueOf(1729057892408L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/main.css\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>모던하우스 공식몰</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <!-- 헤더 시작 -->\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <!-- 헤더 상단 -->\r\n");
      out.write("        <div class=\"header_top\">\r\n");
      out.write("            <h1 class=\"logo\">\r\n");
      out.write("                <a href=\"ModernServlet?command=mdh_main&userid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    <img src=\"./img/tlogo.png\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </h1>\r\n");
      out.write("            <div class=\"mall_switch\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"ModernServlet?command=mdh_main&userid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"link_modern on\">모던몰</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"ModernServlet?command=mdh_sub\" class=\"link_butter\">버터샵</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"search_area\">\r\n");
      out.write("                <input type=\"text\">\r\n");
      out.write("                <a href=\"#\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"top_right\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"ModernServlet?command=mdh_logout\">\r\n");
      out.write("                            <img src=\"./img/icon_logout.png\" alt=\"\">\r\n");
      out.write("                            <span >로그아웃</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"ModernServlet?command=mdh_update_form&userid=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                            <img src=\"./img/icon_mypage.png\" alt=\"\">\r\n");
      out.write("                            <span class=\"join_span\">마이페이지</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./img/icon_cart.png\" alt=\"\">\r\n");
      out.write("                            <span>장바구니</span>\r\n");
      out.write("                            <span class=\"cart_num\">0</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./img/icon_call.png\" alt=\"\">\r\n");
      out.write("                            <span>고객센터</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 헤더 하단 메뉴 부분 -->\r\n");
      out.write("        <div class=\"header_menu\">\r\n");
      out.write("            <div class=\"menu_left\">\r\n");
      out.write("                <div class=\"menu_icon\"></div>\r\n");
      out.write("                <div class=\"cate\">카테고리</div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 마우스 오버 메뉴 -->\r\n");
      out.write("                <div class=\"mainmenu\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">주방</a>\r\n");
      out.write("                            <ul class=\"submenu sub0\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">NEW</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">식기류</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">수저/커트러리</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">컵/잔</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">보틀/텀블러</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">테이블소품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">팬/냄비</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">커피/티 용품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">조리도구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">보관용기</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">주방수납/정리</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">주방잡화</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">패브릭</a>\r\n");
      out.write("                            <ul class=\"submenu sub1\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">NEW</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">침구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">알러지케어</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">담요/블랭킷</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">충전재</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">커튼/블라인드</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">쿠션/방석/패드</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">러그/매트</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">패브릭소품</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">가구</a>\r\n");
      out.write("                            <ul class=\"submenu sub2\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">침실가구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">주방가구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">거실가구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">책상/책장/의자</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">서랍/수납/선반장</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">옷장/행거</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">키즈가구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">택배가구</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">키즈</a>\r\n");
      out.write("                            <ul class=\"submenu sub3\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">키즈플레이</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">키즈침구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">키즈식기/주방</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">키즈욕실</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">키즈가구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">키즈잡화</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">린넨앤키친</a>\r\n");
      out.write("                            <ul class=\"submenu sub4\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">패브릭</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">주방</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">리빙데코</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">욕실/생활</a>\r\n");
      out.write("                            <ul class=\"submenu sub5\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">청소용품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">휴지통/재활용</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">세탁/건조용품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">바디/위생용품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">욕실/생활잡화</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">타올/가운</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">욕실화</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">우산/우의</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">일회용품</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">홈데코</a>\r\n");
      out.write("                            <ul class=\"submenu sub6\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">인테리어 소품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">캔들/디퓨저</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">홈앤가든</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">수납/정리</a>\r\n");
      out.write("                            <ul class=\"submenu sub7\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">의류수납</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">바구니/박스</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">아이템정리</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">선반/트롤리/카트</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">가전/라이프</a>\r\n");
      out.write("                            <ul class=\"submenu sub8\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">가전/디지털</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">여행</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">플레이</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">펫본</a>\r\n");
      out.write("                            <ul class=\"submenu sub9\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">하우스</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">방석/매트/계단</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">장난감</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">식기</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">간식</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">의류</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">액세서리</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">위생용품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">가방</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">뷰티용품</a>\r\n");
      out.write("                            <ul class=\"submenu sub10\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">개인위생용품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">리필용기</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">미용소도구</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">헤어소품</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">시즌잡화</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"ModernServlet?command=mdh_sub\">주전부리</a>\r\n");
      out.write("                            <ul class=\"submenu sub11\">\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">건강간식</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">달콤간식</a></li>\r\n");
      out.write("                                <li><a href=\"ModernServlet?command=mdh_sub\">건강티백</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <ul class=\"menu_right\">\r\n");
      out.write("                <li><a href=\"ModernServlet?command=mdh_sub\">#썸머 핫딜</a></li>\r\n");
      out.write("                <li><a href=\"ModernServlet?command=mdh_sub\">베스트</a></li>\r\n");
      out.write("                <li><a href=\"ModernServlet?command=mdh_sub\">신상품</a></li>\r\n");
      out.write("                <li><a href=\"ModernServlet?command=mdh_sub\">SALE</a></li>\r\n");
      out.write("                <li><a href=\"ModernServlet?command=mdh_sub\">쿠폰/혜택</a></li>\r\n");
      out.write("                <li><a href=\"ModernServlet?command=admin_check\">상품관리</a></li>\r\n");
      out.write("                <li><a href=\"ModernServlet?command=review_list\">REVIEW</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- 우측 하단 고정메뉴 -->\r\n");
      out.write("    <div class=\"right_menu\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img src=\"./img/quick_icon01.png\" alt=\"\">\r\n");
      out.write("                    <span>0</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img src=\"./img/quick_icon02.png\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img src=\"./img/quick_icon03.png\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("		</ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 메인 슬라이더 -->\r\n");
      out.write("    <section class=\"slider\">\r\n");
      out.write("        <div class=\"slide_wrap\">\r\n");
      out.write("            <a class=\"main_img_1\" href=\"#\">\r\n");
      out.write("                <img src=\"./img/main_img_1.gif\" alt=\"\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"main_img_2\" href=\"#\">\r\n");
      out.write("                <img src=\"./img/main_img_2.jpg\" alt=\"\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"main_img_3\" href=\"#\">\r\n");
      out.write("                <img src=\"./img/main_img_3.jpg\" alt=\"\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"main_img_4\" href=\"#\">\r\n");
      out.write("                <img src=\"./img/main_img_4.gif\" alt=\"\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"main_img_5\" href=\"#\">\r\n");
      out.write("                <img src=\"./img/main_img_5.jpg\" alt=\"\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"main_img_6\" href=\"#\">\r\n");
      out.write("                <img src=\"./img/main_img_6.jpg\" alt=\"\">\r\n");
      out.write("            </a>\r\n");
      out.write("            <a class=\"main_img_7\" href=\"#\">\r\n");
      out.write("                <img src=\"./img/main_img_7.jpg\" alt=\"\">\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"main_arrow\">\r\n");
      out.write("            <a href=\"#\"><div class=\"arrow_prev\"></div></a>\r\n");
      out.write("            <a href=\"#\"><div class=\"arrow_next\"></div></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"main_bullet\">\r\n");
      out.write("            <span class=\"main_bullet_on\"></span>\r\n");
      out.write("            <span></span>\r\n");
      out.write("            <span></span>\r\n");
      out.write("            <span></span>\r\n");
      out.write("            <span></span>\r\n");
      out.write("            <span></span>\r\n");
      out.write("            <span class=\"last_bullet\"></span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- 메인 카테고리(주방, 패브릭, 가구 등등) -->\r\n");
      out.write("    <section class=\"main_category\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li class=\"main_list\"></li>\r\n");
      out.write("            <li class=\"main_list\"></li>\r\n");
      out.write("            <li class=\"main_list\"></li>\r\n");
      out.write("            <li class=\"main_list\"></li>\r\n");
      out.write("            <li class=\"main_list\"></li>\r\n");
      out.write("            <li class=\"main_list\"></li>\r\n");
      out.write("            <li class=\"main_list\"></li>\r\n");
      out.write("            <li class=\"main_list\"></li>\r\n");
      out.write("            <li class=\"main_list\"></li>\r\n");
      out.write("            <li class=\"main_list\"></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- 이미지 배너 -->\r\n");
      out.write("    <section class=\"img_banner\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"./sub.html\">\r\n");
      out.write("                    <img src=\"./img/banner_1.jpg\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"./sub.html\">\r\n");
      out.write("                    <img src=\"./img/banner_2.jpg\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- 지금 뜨고 있는 베스트 -->\r\n");
      out.write("    <section class=\"best_prd\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <div class=\"best_title\">\r\n");
      out.write("                <h3>\r\n");
      out.write("                    <a href=\"./sub.html\">지금 뜨고 있는 베스트</a>\r\n");
      out.write("                    <a href=\"./sub.html\">전체보기</a>\r\n");
      out.write("                </h3>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"best_tab\">\r\n");
      out.write("            <li class=\"best_on\">전체</li>\r\n");
      out.write("            <li>주방</li>\r\n");
      out.write("            <li>패브릭</li>\r\n");
      out.write("            <li>가구</li>\r\n");
      out.write("            <li>키즈</li>\r\n");
      out.write("            <li>린넨앤키친</li>\r\n");
      out.write("            <li>욕실/생활</li>\r\n");
      out.write("            <li>홈데코</li>\r\n");
      out.write("            <li>수납/정리</li>\r\n");
      out.write("            <li>가전/라이프</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"best_items\">\r\n");
      out.write("            <dl class=\"item_container\"></dl>\r\n");
      out.write("            <dl class=\"item_container\"></dl>\r\n");
      out.write("            <dl class=\"item_container\"></dl>\r\n");
      out.write("            <dl class=\"item_container\"></dl>\r\n");
      out.write("            <dl class=\"item_container\"></dl>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- 고객님을 위한 맞춤 픽 -->\r\n");
      out.write("    <section class=\"pick_prd\">\r\n");
      out.write("        <h3 class=\"pick_title\">고객님을 위한 맞춤 PICK!</h3>\r\n");
      out.write("        <div class=\"pick_items\">\r\n");
      out.write("            <dl class=\"pick_item_container\"></dl>\r\n");
      out.write("            <dl class=\"pick_item_container\"></dl>\r\n");
      out.write("            <dl class=\"pick_item_container\"></dl>\r\n");
      out.write("            <dl class=\"pick_item_container\"></dl>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- 따끈따끈한 신상품 -->\r\n");
      out.write("    <section class=\"new_prd\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <div class=\"new_title\">\r\n");
      out.write("                <h3>\r\n");
      out.write("                    <a href=\"#\">따끈따끈한 신상품</a>\r\n");
      out.write("                    <a href=\"#\">전체보기</a>\r\n");
      out.write("                </h3>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"slide_cover\">\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("                <dl class=\"slide_card\">\r\n");
      out.write("                    <dt class=\"card_thumnail\">\r\n");
      out.write("                        <img src=\"./img/new_01.jpg\" alt=\"\">\r\n");
      out.write("                        <span>NEW</span>\r\n");
      out.write("                    </dt>\r\n");
      out.write("                    <dd class=\"new_detail\">\r\n");
      out.write("                        <h6>패브릭</h6>\r\n");
      out.write("                        <h3>소프트브리즈 얇은 이불</h3>\r\n");
      out.write("                        <p>온몸을 감싸는 포근함!</p>\r\n");
      out.write("                        <p>부드러움을 극대화한 피치스킨</p>\r\n");
      out.write("                        <p>가공을 한 얇은 차렵이불</p>\r\n");
      out.write("                    </dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"new_bullet\">\r\n");
      out.write("            <span class=\"new_bullet_on\"></span>\r\n");
      out.write("            <span></span>\r\n");
      out.write("            <span></span>\r\n");
      out.write("            <span></span>\r\n");
      out.write("            <span></span>\r\n");
      out.write("            <span></span>\r\n");
      out.write("            <span></span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"new_arrow\">\r\n");
      out.write("            <button class=\"new_arrow_prev\"></button>\r\n");
      out.write("            <button class=\"new_arrow_next\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- 이 달의 모던 픽 -->\r\n");
      out.write("    <section class=\"modern_prd\">\r\n");
      out.write("        <h3 class=\"modern_title\"><a href=\"#\">이 달의 모던 PICK</a></h3>\r\n");
      out.write("        <div class=\"modern_box\">\r\n");
      out.write("            <a href=\"./sub.html\"></a>\r\n");
      out.write("            <a href=\"./sub.html\"></a>\r\n");
      out.write("            <a href=\"./sub.html\"></a>\r\n");
      out.write("            <a href=\"./sub.html\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- 주목해야할 기획전 -->\r\n");
      out.write("    <section class=\"plan_prd\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <div class=\"plan_title\">\r\n");
      out.write("                <h3>\r\n");
      out.write("                    <a href=\"#\">주목해야 할 기획전</a>\r\n");
      out.write("                    <a href=\"#\">전체보기</a>\r\n");
      out.write("                </h3>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"plan_items\">\r\n");
      out.write("                <div class=\"plan_left\">\r\n");
      out.write("                    <div class=\"plan_left_top\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./img/plan_01.jpg\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"plan_left_bottom\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./img/plan_03.jpg\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./img/plan_04.jpg\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./img/plan_05.jpg\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"plan_right\">\r\n");
      out.write("                    <div class=\"plan_left_top\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./img/plan_02.jpg\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"plan_left_bottom\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./img/plan_06.jpg\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./img/plan_07.jpg\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"./img/plan_08.jpg\" alt=\"\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- 모던 엠디의 추천 -->\r\n");
      out.write("    <section class=\"recom_prd\">\r\n");
      out.write("        <h3 class=\"pick_title\">모던 MD의 추천</h3>\r\n");
      out.write("        <div class=\"recom_box\">\r\n");
      out.write("            <div class=\"recom_box_banner\">\r\n");
      out.write("                <a href=\"#\">\r\n");
      out.write("                    <img src=\"./img/recom_banner_01.jpg\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <dl class=\"recom_item_container\"></dl>\r\n");
      out.write("            <dl class=\"recom_item_container\"></dl>\r\n");
      out.write("            <dl class=\"recom_item_container\"></dl>\r\n");
      out.write("            <dl class=\"recom_item_container\"></dl>\r\n");
      out.write("            <dl class=\"recom_item_container\"></dl>\r\n");
      out.write("            <dl class=\"recom_item_container\"></dl>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- 매장찾기, 버터샵, 키즈관 -->\r\n");
      out.write("    <section class=\"store_banner\">\r\n");
      out.write("        <div class=\"store_banner_container\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <img src=\"./img/store_banner_01.jpg\" alt=\"\">\r\n");
      out.write("                        <span>매장찾기</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <img src=\"./img/store_banner_02.jpg\" alt=\"\">\r\n");
      out.write("                        <span>버터샵</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <img src=\"./img/store_banner_03.jpg\" alt=\"\">\r\n");
      out.write("                        <span>키즈관</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- 푸터 시작 -->\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        <div class=\"footer_box\"> \r\n");
      out.write("            <div class=\"logobox\">\r\n");
      out.write("                <div class=\"ftlogo\">\r\n");
      out.write("                    <a href=\"#\">\r\n");
      out.write("                        <img src=\"./img/flogonew.png\" alt=\"\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <ul class=\"snslogo\">\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"./img/footer_sns01.png\" alt=\"\"></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"./img/footer_sns03.png\" alt=\"\"></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"./img/footer_sns04.png\" alt=\"\"></a></li>\r\n");
      out.write("                    <li><a href=\"#\"><img src=\"./img/footer_sns05.png\" alt=\"\"></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"infobox\">\r\n");
      out.write("                <div class=\"linklist\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">회사소개</a></li>\r\n");
      out.write("                        <li><a href=\"#\">IR</a></li>\r\n");
      out.write("                        <li><a href=\"#\">공지사항</a></li>\r\n");
      out.write("                        <li><a href=\"#\">FAQ</a></li>\r\n");
      out.write("                        <li><a href=\"#\">1:1문의</a></li>\r\n");
      out.write("                        <li><a href=\"#\">대량/제휴문의</a></li>\r\n");
      out.write("                        <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("                        <li><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"companyinfo\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>주소 : 서울특별시 구로구 경인로 662 (디큐브시티) 14층</li>\r\n");
      out.write("                        <li>회사명 : MH&CO.</li>\r\n");
      out.write("                        <li>대표이사 : 오상흔</li>\r\n");
      out.write("                        <li>사업자등록번호 : 821-87-00617</li>\r\n");
      out.write("                        <li>통신판매업번호 : 2017-서울구로-1368</li>\r\n");
      out.write("                        <li>개인정보책임자 : 이효영</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"certifyinfo\">\r\n");
      out.write("                    <span>고객님은 안전거래를 위해 결제 시 저희 사이트에서 가입한 구매안전 서비스를 이용하실 수 있습니다.</span>\r\n");
      out.write("                    <a href=\"#\">KCP 가입 확인</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p>copyright. 2020. modernhousemall.com. All rights reserved.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"csbox\">\r\n");
      out.write("                <h3>고객문의 대표전화</h3>\r\n");
      out.write("                <h2>1899-0811</h2>\r\n");
      out.write("                <p>AM 09:00 ~ PM 06:00 <br>(주말 · 공휴일 휴무)</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>  \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\" src=\"script/motion.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
